### ISSUE TITLE
yeni nesil amd ekran kartları için kernel ayarları eklenmeli

### ISSUE THREAD

**Issue by hrngultekin** [pisilinux/core#1099]
kernel 5.6.4 sürümünde eklenmiş olan amdgpu ayarları tekrar eklenmeli
bu ayarlar eklenirse amd cihazlardaki siyah ekran sorunu da çözülebilir

**Comment by suvari** [comment]
Harun Bey, uyarınız bizi hep aydınlatır, derhal eklendi...
Bizi yalnız bırakmayın, desteklerinizi hissetmek çok güzel.
https://github.com/pisilinux/core/commit/f6c347184754d7a4b1179d78af665f2218c649df

**Comment by hrngultekin** [comment]
Hızlı dönüşünüz için teşekkür ederim. Elimden geldiği kadar desteklemeye devam edeceğim

**Comment by suvari** [comment]
Biz teşekkür ederiz, devel davetiyeniz mailinizde, kesinlikle bekleriz...
