### ISSUE TITLE
 libthread_db_1-0.so bulunamadı hatası

### ISSUE THREAD

**Issue by hknyldz** [pisilinux/core#118]
Kurulumdan sonra açılırken kde çöküyor. Hata ayıkla diyince  libthread_db_1-0.so bulunamadı hatası veriyor.

**Comment by ertugerata** [comment]
$ pisi sf /lib/libthread_db-1.0.so
/lib/libthread_db-1.0.so aranıyor
glibc paketi içinde lib/libthread_db-1.0.so dosyası var.

burada @suvari  yapıştırdığıba a-bakacak olursak http://paste2.org/csebbbLN

warning: File "/lib/libthread_db-1.0.so" auto-loading has been declined by your auto-load safe-path' set to "$debugdir:$datadir/auto-load" 

Bu satır önemli. Bu satırdan o dosya yok değil, başka bir şey anlamak lazım. Ayrıca debug dosyalarını oluşturmuyoruz. dosya içerisindeki bir çok sey onu ifade ediyor.

**Comment by ertugerata** [comment]
bu core hatası değil, aranan dosya glibc içerisinde mevcut. devam ediyor ise yeniden açınız..
