### ISSUE TITLE
swap alanı

### ISSUE THREAD

**Issue by suvari** [pisilinux/core#121]
format atarken, swap alanı oluşturmaktan vazgeçmek gerekiyor. aksi takdirde "disk, ext4 olarak biçimlendiriliyor.." bölümünde, donup kalıyor, format devam etmiyor. sadece mouse çalışmaya devam ediyor.

**Comment by ertugerata** [comment]
önceden ayarlanmış swap var ise onu fstab a aklemiş mi kontrol edebilir misiniz?

**Comment by suvari** [comment]
önceden ayarlanmış swap vardı ve fstab a eklenmiş, ilginç. kinfocenter üzerinde de gözüküyor, ama bu swap alanını format sırasında ekleyememiştim ben.

**Comment by ertugerata** [comment]
kurulumda yalı ile ilgili işlem yapılmaması durumunda problem yok.

**Comment by suvari** [comment]
fixed, close, pls
