### ISSUE TITLE
krunner (deleted)

### ISSUE THREAD

**Issue by suvari** [pisilinux/core#123]
ilk güncelleme sonrasında bu hata çıkıyor:

GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
/usr/bin/krunner (deleted): Böyle bir dosya ya da dizin yok.
Attaching to process 869
/usr/bin/krunner (deleted): Böyle bir dosya ya da dizin yok.
(gdb)

**Comment by ertugerata** [comment]
bu is biraz karıştı ? 

ertugerata@pisi_linux2 ~ $ uname -a
Linux pisi_linux2.0alfa5 4.1.7 #1 SMP Fri Sep 18 10:08:14 EEST 2015 x86_64 GNU/Linux
ertugerata@pisi_linux2 ~ $ pisi sf `which krunner`
/usr/bin/krunner aranıyor
plasma-workspace paketi içinde usr/bin/krunner dosyası var.

**Comment by ertugerata** [comment]
krunner var ve çalışıyor, bu alt+space veya alt+f2 ye basın çıkacak. 
çıkmıyor ise bu hatayı main e açar mısınız?
