### ISSUE TITLE
güncelleme sonrasında, sudo pisi up -dvs ile çıkan paketlerin listesi

### ISSUE THREAD

**Issue by suvari** [pisilinux/core#124]
sudo pisi up -dvs ile çıkan paketlerin listesi, aşağıdaki şekildedir, bildirdiğim son 3-4 issue bunlarla ilgili olabilir mi diye belirtmek istedim .

Aşağıdaki paketler yükseltilecektir:
ark                      dolphin          dragonplayer  gobject-introspection
gstreamer                kate             kdebaseapps   kunitconversion      
module-virtualbox-guest  ntfs-3g          ntfsprogs     polkit-qt            
pulseaudio               pulseaudio-libs  qt5-base      qt5-declarative      
qt5-designer             qt5-qdbusviewer  qt5-quick1    qt5-quickcontrols    
qt5-script               qt5-sensors      qt5-svg       qt5-xmlpatterns      
tar                      yakuake

**Comment by ertugerata** [comment]
bunlar güncellendikten sonra hala aynı hatalar var mı yoksa yeni hatalar mı çıktı?

**Comment by suvari** [comment]
bunlar, güncelledikten sonra da devam eden hatalar , 
sadece grub un, 1.2 pisi kurulu diğer diski görememesi sorunu, kernel güncellemesinden sonra çıktı bende, dewil de yaşamış aynı sorunu.

**Comment by ertugerata** [comment]
bu hata düzelmiş olması lazım @suvari

**Comment by ertugerata** [comment]
kapatıyorum. eğer devam ediyorsa açınız @suvari
