### ISSUE TITLE
consolekit güncellenirken, "run-session.d sistemde bulunamadı.."

### ISSUE THREAD

**Issue by suvari** [pisilinux/core#126]
alfa5 ile güncellenirken, consolekit ile ilgili bir ayrıntı: http://paste2.org/jyI8nmUt
hata mıdır anlayamadım aslında, nolur nolmaz diye ekledim :)

**Comment by ertugerata** [comment]
uyarı, yeni consolekit'de oraya bir şey koyduk eskisinde de olması gerek zannediyor.
