### ISSUE TITLE
kernel 4.2.2 sonrası grep..

### ISSUE THREAD

**Issue by suvari** [pisilinux/core#129]
https://paste.kde.org/ptltcvz4i
sitem açılmadı
ancak grub diğer disklerdeki sistemleri gösterir oldu
açılışta tepede çıkan iki satırlık init hatası, tek satır halinde çıkıyor, yazı aynı
init hatasının olduğu yeri geçemiyor makine
eski kernel ile açtım

**Comment by ertugerata** [comment]
yeni kernel ile deneyebilir misiniz?

**Comment by suvari** [comment]
kernel 4.2.3 ile de sistem açılmıyor, hata aynı. bu kernelden sonra, grub diğer disktekilerden sadece birini (win7) algılyor,diğerleri gözükmüyor.

**Comment by ertugerata** [comment]
Grub guncellemesi ile diger isletim sistemlerini gorememe hallolmus olmali. Tabii ki grub.conf u grub2-mkconfig ile olusturmalisiniz. 
Sistemin acilmamasi herhangi bir hata veriyor mu? Ekran goruntusu vs lazim

**Comment by ertugerata** [comment]
haber bekleniyor @suvari

**Comment by ertugerata** [comment]
problem varsa yeniden açarsınız @suvari
