### ISSUE TITLE
ndiswrapper

### ISSUE THREAD

**Issue by alick01** [pisilinux/core#133]
ndiswrapper başarısız http://ciftlik.pisilinux.org/ciftlik/compiledetail/914

**Comment by ertugerata** [comment]
@ilkermanap ndiswrapper de build için önce kernel kurulmasını istiyor. Onu da istisna listesine alalım.

**Comment by ertugerata** [comment]
builded.

**Comment by ilkermanap** [comment]
ndiswrapper kernel gerektiren paketler arasina alindi.. yeniden derleme basarili..
