### ISSUE TITLE
grub cfg kernel panic çözümü

### ISSUE THREAD

**Issue by hrngultekin** [pisilinux/core#1453]
https://github.com/pisilinux/core/blob/master/system/boot/grub2/files/30_os-prober2

210. satır aşağıdaki kod ile değiştirilmeli

```LINITRD="`echo ${LINUX} | cut -d ':' -f 5 | tr '^' ' '`"```

**Comment by suvari** [comment]
Eklendi, teşekkürler Harun Bey
