### ISSUE TITLE
kdm lines..

### ISSUE THREAD

**Issue by suvari** [pisilinux/core#158]
line 179  262 https://github.com/pisilinux/core/blob/c0b2d3ce7ee02f6ecce5332cd98adbf06364e4c2/system/base/baselayout/comar/package.py

line 30 ve 338 https://github.com/pisilinux/core/blob/c0b2d3ce7ee02f6ecce5332cd98adbf06364e4c2/system/base/baselayout/comar/usermgr.py
sddm satırları düzenlenmeli...

**Comment by ertugerata** [comment]
baselayout $ grep -r kdm
files/services:kdm             2115/tcp                # Key Distribution Manager
files/services:kdm             2115/udp                # Key Distribution Manager
comar/package.py:                (165, "kdm"),
comar/package.py:                (165, "kdm", "kdm", "/var", "/sbin/nologin", "", ["kdm"], [], []),
comar/usermgr.py:    "/usr/share/kde4/apps/kdm/pics/users",
comar/usermgr.py:        faces = glob.glob("/usr/share/*/apps/kdm/pics/users/*.png")

**Comment by alihanozturk** [comment]
sddm ile ilgili sorunlarımız bundan kaynaklı olma ihtimali.
