### ISSUE TITLE
some packages build fail in farmv2

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/core#376]
- [ ] patch //  http://ciftlik.pisilinux.org/ciftlik/compiledetail/5212 
- [x] glibc  // http://ciftlik.pisilinux.org/ciftlik/compiledetail/5209 
- [x] gcc // http://ciftlik.pisilinux.org/ciftlik/compiledetail/5158
- [x] lvm2 // http://ciftlik.pisilinux.org/ciftlik/compiledetail/5001

**Comment by suvari** [comment]
Fixed.
