### ISSUE TITLE
Firmware bug

### ISSUE THREAD

**Issue by alihanozturk** [pisilinux/core#409]
[Firmware Bug]: ACPI: No _BQC method, cannot determine initial brightness

[Firmware Bug]: ACPI: BIOS _OSI(Linux) query ignored

**Comment by ayhanyalcinsoy** [comment]
Hata devam etmesine rağmen ekran aydınlatması değiştirilebiliyor. Hata kapanabilir.

**Comment by ertugerata** [comment]
OK
