### ISSUE TITLE
Kernel hatası

### ISSUE THREAD

**Issue by SamiBabat** [pisilinux/core#437]
Kernel son versiyon yüklendi  Ama sistem eski kernel'i gösteriyor.

uname -r çıktısı:  4.4.8
Xorg.0.log :  [19.611] Kernel command line: BOOT_IMAGE=/boot/kernel-4.4.8 root=UUID=569b2cf0-f5fd-4b8b-9c58-8b67e990469e ro quiet splash resume=UUID=04659845-2042-4f11-b34b-485c961eaf33
pisi info kernel : 
Yüklü paket:
İsim                : kernel, sürüm: 4.6.3, yayım: 3
Özet                : Pisi Linux için Linux çekirdeği

grub.cfg :  https://gist.github.com/SamiBabat/ddb3879dec413a3c5c8cd3b4ac87d0d8

**Comment by ertugerata** [comment]
grub.conf unu buraya ekleyebilir misin

**Comment by ertugerata** [comment]
bunu tam okuyamadım bir yere yapıştırsan da gist felan buraya link versen daha iyi olmaz mıydı

**Comment by SamiBabat** [comment]
Grub kaynaklı bir sorunmuş. Pisi 1.2 Grubu kaldırıp 2.0 grub yükleyince sorun çözüldü.
