### ISSUE TITLE
Pisi açılırken  init/line cant create ile başlayan bir hata görülüyor

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/core#47]
http://bugs.pisilinux.org/index.php?do=details&task_id=142

**Comment by ertugerata** [comment]
init dosyasında hotplug ile ilgili bir dizin oluşturulamadı hatası

**Comment by burakerturk** [comment]
bakalım abi

**Comment by alihanozturk** [comment]
can't create /proc/sys/kernel/hotplug
