### ISSUE TITLE
ndiswrapper depoya alınmalı

### ISSUE THREAD

**Issue by ghost** [pisilinux/core#49]
https://github.com/pisilinux/pisilife/tree/master/ndiswrapper

**Comment by ertugerata** [comment]
kernel-4 serisi için yama ve ya sürüm bekleniyor

**Comment by ertugerata** [comment]
131ac8eba58 ~ # pisi bi /git/core/kernel/drivers/ndiswrapper/pspec.xml -d --ignore-safety 
Building source package: ndiswrapper
DEBUG: InstallDB initialized in 0.000358104705811.
ndiswrapper-1.59.tar.gz [cached]
Unpacking archive(s)...
 unpacked (/var/pisi/ndiswrapper-1.59-1/work)
Setting up source...
Building source...                                                                                                                                                                              
Sandbox enabled build...
patching file driver/crt.c
patching file driver/ntoskernel.h
DEBUG: return value for "patch -p1 < ndiswrapper-1.59.patch" is 0
make: Entering directory '/var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver'
make -C /usr/src/linux-headers-4.1.2 M=/var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver
make[1]: Entering directory '/usr/src/linux-headers-4.1.2'
  MKEXPORT /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/hal_exports.h
  MKEXPORT /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/ndis_exports.h
  MKEXPORT /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/crt_exports.h
  MKEXPORT /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/ntoskernel_exports.h
  LD      /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/built-in.o
  MKEXPORT /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/ntoskernel_io_exports.h
  MKEXPORT /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/rtl_exports.h
  MKEXPORT /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/usb_exports.h
  MKSTUBS /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/win2lin_stubs.h
  CC [M]  /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/crt.o
  CC [M]  /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/hal.o
  CC [M]  /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/iw_ndis.o
  CC [M]  /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/loader.o
  CC [M]  /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/ndis.o
/var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/ndis.c: In function 'read_setting':
/var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/ndis.c:441:3: error: implicit declaration of function 'strnicmp' [-Werror=implicit-function-declaration]
   if (strnicmp(keyname, setting->name, length) == 0) {
   ^
  CC [M]  /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/ntoskernel.o
  CC [M]  /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/ntoskernel_io.o
  CC [M]  /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/pe_linker.o
  CC [M]  /var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/pnp.o
cc1: some warnings being treated as errors
scripts/Makefile.build:258: recipe for target '/var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/ndis.o' failed
make[2]: *** [/var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver/ndis.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:1383: recipe for target '_module_/var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver' failed
make[1]: *** [_module_/var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.1.2'
Makefile:183: recipe for target 'modules' failed
make: *** [modules] Error 2
make: Leaving directory '/var/pisi/ndiswrapper-1.59-1/work/ndiswrapper-1.59/driver'
DEBUG: return value for "make -j5 -C driver KVERS_UNAME=4.1.2" is 2
Traceback (most recent call last):
  File "/git/core/kernel/drivers/ndiswrapper/actions.py", line 18, in build
    autotools.make("-C driver KVERS_UNAME=%s" % KDIR)
  File "/usr/lib/pisilinux/pisi/actionsapi/autotools.py", line 103, in make
    if system('make %s %s' % (get.makeJOBS(), parameters)):
  File "/usr/lib/pisilinux/pisi/actionsapi/shelltools.py", line 255, in system
    error(_("Command \"%s\" failed, return value was %d.") % (command, retValue))
  File "/usr/lib/pisilinux/pisi/actionsapi/__init__.py", line 27, in error
    raise Error(msg)
pisi.actionsapi.Error: Command "make -j5 -C driver KVERS_UNAME=4.1.2" failed, return value was 2.
Action script error caught.
*** 1 error(s), 0 warning(s)
Program terminated.
Please use 'pisi help' for general help.
