### ISSUE TITLE
initramfs/init cannot find media...

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/core#630]
![img_20170322_162114_1024](https://cloud.githubusercontent.com/assets/225387/24246642/19433068-0fd1-11e7-8ff1-bf1189f4e2a3.jpg)

![img_20170322_162248_1024](https://cloud.githubusercontent.com/assets/225387/24246677/3d35c3f0-0fd1-11e7-8620-03c3a1b8936e.jpg)

**Comment by ertugerata** [comment]
isohybrid ile ilgili bir sorun. iso cd ye yazıldığında boot ettiği raporlandı @rmys

**Comment by eersoy93** [comment]
ISO dosyasının bağlantısı nerede?

**Comment by ertugerata** [comment]
fix with https://github.com/pisilinux/core/commit/1f1ad0824ccf4934c2f8d710dd1ecf751b386c5b
