### ISSUE TITLE
libcryptsetup eksik dep

### ISSUE THREAD

**Issue by aydemir** [pisilinux/core#65]
libcryptsetup-1.6.7-7-p01-x86_64.pisi [cached]
Installing libcryptsetup, version 1.6.7, release 7
device-mapper dependency of package libcryptsetup is not satisfied
Program terminated.
libcryptsetup package cannot be installed unless the dependencies are satisfied
Please use 'pisi help' for general help

**Comment by ertugerata** [comment]
device-mapper hardware.disk, libcryptsetup system.base base da olduğu için bu hata meydana geliyor. 

libcryptsetup paketini system.base dan util.crypt e alarak denemek lazım.
