### ISSUE TITLE
follow newest stable kernel

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/core#85]
sync with mageia http://svnweb.mageia.org/packages/cauldron/kernel/releases

**Comment by ertugerata** [comment]
4.1.5 first build https://github.com/pisilinux/core/commit/7e6b1819d0ec9e93788d2b8f9d2d20784fa37b26

**Comment by ertugerata** [comment]
4.1.5 in core https://github.com/pisilinux/core/commit/025a25a3315d4f32addb7165bc9e38ae1aa336c1

**Comment by ertugerata** [comment]
4.2.2 in core https://github.com/pisilinux/core/commit/591cc458dc032625f41b89a37c94f7b3a74b7c34

**Comment by ertugerata** [comment]
4.2.3 in core https://github.com/pisilinux/core/commit/80dff6ca707340cc17f5279e3c0c22c44065a658

**Comment by ertugerata** [comment]
4.2.4 in core https://github.com/pisilinux/core/commit/5ae938f4330ff93ffa47435d22a089b880095dcb

**Comment by ertugerata** [comment]
https://github.com/pisilinux/core/commit/966fa05e9500cae1a9542f56a10ccbbbaa53b2a6 4.3.0 kernel in core

**Comment by ertugerata** [comment]
https://github.com/pisilinux/core/commit/f791d2e35dbdba42b45d7b9157d1a465620ec6a1 4.4.0 in core

**Comment by ertugerata** [comment]
https://github.com/pisilinux/core/commit/c27846265fd1d198eb05ecb747bb5dc06e189903 4.6.3 in repo

**Comment by suvari** [comment]
Fixed
