### ISSUE TITLE
b43 firmware yok.

### ISSUE THREAD

**Issue by hknyldz** [pisilinux/core#92]
kablosuz bağlanmak için 2.0 için b43-firmware gerekiyor repoda yok 
https://www.kernel.org/pub/linux/kernel/projects/backports/stable/v4.1.1/

**Comment by ertugerata** [comment]
https://github.com/pisilinux/main/commit/bc3e6c020e3d1f8655e63b00f0ef8cb9727e5e27 closed in main.
